sudo: false

language: node_js
node_js:
  - 12.13.0

before_install:
  - npm install coveralls

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master

script:
  - npm run test:cov
  - npm run storybook:ci
  - npm run test:cypress
